=== rreganjr/Requel/trunk/test/resources/xml/project.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" targetNamespace="http://www.people.fas.harvard.edu/~rregan/requel" xmlns:tns="http://www.people.fas.harvard.edu/~rregan/requel" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="actor" type="tns:actor"/>

  <xs:element name="argument" type="tns:argument"/>

  <xs:element name="changeSpellingPosition" type="tns:changeSpellingPosition"/>

  <xs:element name="domainAdminUserRole" type="tns:domainAdminUserRole"/>

  <xs:element name="goal" type="tns:goal"/>

  <xs:element name="goalRelation" type="tns:goalRelation"/>

  <xs:element name="issue" type="tns:issue"/>

  <xs:element name="note" type="tns:note"/>

  <xs:element name="organization" type="tns:organization"/>

  <xs:element name="position" type="tns:position"/>

  <xs:element name="project" type="tns:project"/>

  <xs:element name="projectPermission" type="tns:projectPermission"/>

  <xs:element name="projectUserRole" type="tns:projectUserRole"/>

  <xs:element name="stakeholder" type="tns:stakeholder"/>

  <xs:element name="systemAdminUserRole" type="tns:systemAdminUserRole"/>

  <xs:element name="team" type="tns:team"/>

  <xs:element name="user" type="tns:user"/>

  <xs:element name="userPermission" type="tns:userPermission"/>

  <xs:complexType name="abstractAnnotation" abstract="true">
    <xs:sequence>
      <xs:element name="annotations" form="qualified" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
              <xs:element ref="tns:issue"/>
              <xs:element ref="tns:note"/>
            </xs:choice>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="text" type="xs:string" form="qualified" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="createdBy" type="xs:IDREF"/>
    <xs:attribute name="dateCreated" type="xs:string"/>
    <xs:attribute name="id" type="xs:ID"/>
  </xs:complexType>

  <xs:complexType name="user">
    <xs:sequence>
      <xs:element name="username" type="xs:string" form="qualified"/>
      <xs:element name="password" type="xs:string" form="qualified"/>
      <xs:element name="name" type="xs:string" form="qualified" default=""/>
      <xs:element name="emailAddress" type="xs:string" form="qualified" minOccurs="0"/>
      <xs:element name="phoneNumber" type="xs:string" form="qualified" minOccurs="0"/>
      <xs:element ref="tns:organization"/>
      <xs:element name="userRoles" form="qualified" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
              <xs:element ref="tns:domainAdminUserRole"/>
              <xs:element ref="tns:projectUserRole"/>
              <xs:element ref="tns:systemAdminUserRole"/>
            </xs:choice>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="editable" type="xs:boolean" form="qualified"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID"/>
  </xs:complexType>

  <xs:complexType name="organization">
    <xs:sequence/>
    <xs:attribute name="name" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="abstractUserRole" abstract="true">
    <xs:sequence>
      <xs:element name="userPermissions" form="qualified" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element ref="tns:userPermission" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="userPermission">
    <xs:sequence/>
    <xs:attribute name="id" type="xs:string"/>
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="userRoleType" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="argument">
    <xs:sequence>
      <xs:element name="text" type="xs:string" form="qualified" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="createdBy" type="xs:IDREF"/>
    <xs:attribute name="dateCreated" type="xs:string"/>
    <xs:attribute name="id" type="xs:ID"/>
    <xs:attribute name="supportLevel" type="tns:argumentPositionSupportLevel"/>
  </xs:complexType>

  <xs:complexType name="changeSpellingPosition">
    <xs:complexContent>
      <xs:extension base="tns:position">
        <xs:sequence/>
        <xs:attribute name="propertyName" type="xs:string"/>
        <xs:attribute name="correctWord" type="xs:string"/>
        <xs:attribute name="misspelledWord" type="xs:string"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="position">
    <xs:sequence>
      <xs:element name="arguments" form="qualified" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element ref="tns:argument" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="text" type="xs:string" form="qualified" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="createdBy" type="xs:IDREF"/>
    <xs:attribute name="dateCreated" type="xs:string"/>
    <xs:attribute name="id" type="xs:ID"/>
  </xs:complexType>

  <xs:complexType name="issue">
    <xs:complexContent>
      <xs:extension base="tns:abstractAnnotation">
        <xs:sequence>
          <xs:element name="positions" form="qualified" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                  <xs:element ref="tns:position"/>
                  <xs:element ref="tns:changeSpellingPosition"/>
                </xs:choice>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
        <xs:attribute name="mustBeResolved" type="xs:boolean" use="required"/>
        <xs:attribute name="resolvedByPosition" type="xs:IDREF"/>
        <xs:attribute name="resolvedByUser" type="xs:IDREF"/>
        <xs:attribute name="dateResolved" type="xs:string"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="note">
    <xs:complexContent>
      <xs:extension base="tns:abstractAnnotation">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="domainAdminUserRole">
    <xs:complexContent>
      <xs:extension base="tns:abstractUserRole">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="projectUserRole">
    <xs:complexContent>
      <xs:extension base="tns:abstractUserRole">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="abstractProjectOrDomain" abstract="true">
    <xs:sequence>
      <xs:element name="goals" form="qualified" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element ref="tns:goal" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="name" type="xs:string" form="qualified" minOccurs="0"/>
      <xs:element name="stakeholders" form="qualified" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element ref="tns:stakeholder" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="teams" form="qualified" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element ref="tns:team" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="createdBy" type="xs:IDREF"/>
    <xs:attribute name="dateCreated" type="xs:string"/>
    <xs:attribute name="id" type="xs:ID"/>
  </xs:complexType>

  <xs:complexType name="goal">
    <xs:complexContent>
      <xs:extension base="tns:abstractTextEntity">
        <xs:sequence>
          <xs:element name="goalRelations" form="qualified" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element ref="tns:goalRelation" minOccurs="0" maxOccurs="unbounded"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="abstractTextEntity" abstract="true">
    <xs:complexContent>
      <xs:extension base="tns:abstractProjectOrDomainEntity">
        <xs:sequence>
          <xs:element name="text" type="xs:string" form="qualified" minOccurs="0"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="abstractProjectOrDomainEntity" abstract="true">
    <xs:sequence>
      <xs:element name="annotations" form="qualified" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
              <xs:element ref="tns:issue"/>
              <xs:element ref="tns:note"/>
            </xs:choice>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="name" type="xs:string" form="qualified" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="createdBy" type="xs:IDREF"/>
    <xs:attribute name="dateCreated" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="goalRelation">
    <xs:sequence/>
    <xs:attribute name="createdBy" type="xs:IDREF"/>
    <xs:attribute name="dateCreated" type="xs:string"/>
    <xs:attribute name="id" type="xs:ID"/>
    <xs:attribute name="relationType" type="xs:string"/>
    <xs:attribute name="toGoal" type="xs:IDREF"/>
  </xs:complexType>

  <xs:complexType name="stakeholder">
    <xs:complexContent>
      <xs:extension base="tns:abstractProjectOrDomainEntity">
        <xs:sequence>
          <xs:element name="goals" form="qualified" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="goalRef" type="xs:IDREF" minOccurs="0" maxOccurs="unbounded"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="projectPermissions" form="qualified" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element ref="tns:projectPermission" minOccurs="0" maxOccurs="unbounded"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element ref="tns:user"/>
        </xs:sequence>
        <xs:attribute name="team" type="xs:IDREF"/>
        <xs:attribute name="id" type="xs:ID"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="projectPermission">
    <xs:sequence/>
    <xs:attribute name="entityType" type="xs:string"/>
    <xs:attribute name="permissionType" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="team">
    <xs:complexContent>
      <xs:extension base="tns:abstractProjectOrDomainEntity">
        <xs:sequence>
          <xs:element name="members" form="qualified" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="stakeholderRef" type="xs:IDREF" form="qualified" minOccurs="0" maxOccurs="unbounded"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="actor">
    <xs:complexContent>
      <xs:extension base="tns:abstractProjectOrDomainEntity">
        <xs:sequence>
          <xs:element name="goals" form="qualified" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element ref="tns:goal" minOccurs="0" maxOccurs="unbounded"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="project">
    <xs:complexContent>
      <xs:extension base="tns:abstractProjectOrDomain">
        <xs:sequence>
          <xs:element name="annotations" form="qualified" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                  <xs:element ref="tns:issue"/>
                  <xs:element ref="tns:note"/>
                </xs:choice>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element ref="tns:organization"/>
          <xs:element name="status" type="xs:string" form="qualified" minOccurs="0"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="systemAdminUserRole">
    <xs:complexContent>
      <xs:extension base="tns:abstractUserRole">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:simpleType name="argumentPositionSupportLevel">
    <xs:restriction base="xs:string">
      <xs:enumeration value="StronglyFor"/>
      <xs:enumeration value="For"/>
      <xs:enumeration value="Neutral"/>
      <xs:enumeration value="Against"/>
      <xs:enumeration value="StronglyAgainst"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== rreganjr/Requel/test/resources/xml/Requel.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<project id="POD_1" revision="19"
	dateCreated="2009-01-04T04:14:06"
	createdBy="USR_5"
	xmlns="http://www.people.fas.harvard.edu/~rregan/requel"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.people.fas.harvard.edu/~rregan/requel project.xsd">

    <actors>
        <actor id="ACT_3" revision="10" dateCreated="2009-01-05T03:12:23" createdBy="USR_5">
            <text>The automated assistant is part of the system, but interacts with parts of the system like a project user. The automated assistant will be a stakeholder on all projects.</text>
            <goals/>
            <name>Automated Assistant</name>
        </actor>
        <actor id="ACT_1" revision="8" dateCreated="2009-01-05T03:09:06" createdBy="USR_5">
            <text>Project users use the system to create requirments in projects.</text>
            <goals/>
            <name>Project User</name>
        </actor>
        <actor id="ACT_2" revision="8" dateCreated="2009-01-05T03:09:50" createdBy="USR_5">
            <text>System administrator users create other users and manage the system level user permissions.</text>
            <goals/>
            <name>System Admin</name>
        </actor>
    </actors>
    <glossary/>
    <goals>
        <goal id="GOL_9" revision="7" dateCreated="2009-01-04T05:52:58" createdBy="USR_5">
            <text>The system analyzes the requirement elements as they are added to a project and makes suggestions by adding issues to the elements.</text>
            <name>Automatted Assistance</name>
            <goalRelations/>
        </goal>
        <goal id="GOL_1" revision="8" dateCreated="2009-01-04T04:18:02" createdBy="USR_5">
            <text>A team of technical and business stakeholders can use the system to create accurate, precise and unambiguous system requirements.</text>
            <name>Collaborative Elicitation of Requirements</name>
            <goalRelations/>
        </goal>
        <goal id="GOL_7" revision="5" dateCreated="2009-01-04T05:35:43" createdBy="USR_5">
            <text>The system supports integrated discussion of the requirements such that stakeholders can identify issues with the project elements, state multiple solutions to each issue, and pros and cons of each solution.</text>
            <name>Discussion of Requirements</name>
            <goalRelations/>
        </goal>
        <goal id="GOL_6" revision="7" dateCreated="2009-01-04T04:49:52" createdBy="USR_5">
            <text>The system is easy to use so that non-technical users can contribute to the requirements without the need for specialized skills or training.</text>
            <name>Easy to Use</name>
            <goalRelations/>
        </goal>
        <goal id="GOL_4" revision="6" dateCreated="2009-01-04T04:39:54" createdBy="USR_5">
            <text>The system does not force a specific requirements elicitation process on the stakeholders. The system does not require the stakeholders to use all the features of the system.</text>
            <name>Flexible Process and Deliverables</name>
            <goalRelations>
                <goalRelation toGoal="GOL_6" relationType="Supports" id="GLR_1" dateCreated="2009-01-04T04:50:17" createdBy="USR_5">
                    <annotations/>
                </goalRelation>
            </goalRelations>
        </goal>
        <goal id="GOL_2" revision="6" dateCreated="2009-01-04T04:22:52" createdBy="USR_5">
            <text>Using the system improves understanding of the requirements by all the stakeholders compared to non-integrated tools such as emails and spreadsheets.</text>
            <name>Improved Understanding</name>
            <goalRelations/>
        </goal>
        <goal id="GOL_8" revision="4" dateCreated="2009-01-04T05:39:55" createdBy="USR_5">
            <text>The system notifies the stakeholders of changes to the project. The user can customize how the notifications occur: every time a change is made, or a periodic summary.</text>
            <name>Notification of Project Changes</name>
            <goalRelations/>
        </goal>
        <goal id="GOL_5" revision="7" dateCreated="2009-01-04T04:48:15" createdBy="USR_5">
            <text>The requirements are defined in natural language such that non-technical users do not need specialized skills to understand the requirements.</text>
            <name>Requirements defined in Natural Language</name>
            <goalRelations>
                <goalRelation toGoal="GOL_6" relationType="Supports" id="GLR_2" dateCreated="2009-01-04T04:50:51" createdBy="USR_5">
                    <annotations/>
                </goalRelation>
            </goalRelations>
        </goal>
        <goal id="GOL_10" revision="13" dateCreated="2009-01-05T02:19:00" createdBy="USR_5">
            <text>The work done on the thesis is exclusively done by the student.</text>
            <name>Work is your own</name>
            <goalRelations/>
        </goal>
    </goals>
    <name>Requel</name>
    <reports/>
    <scenarios/>
    <stakeholders>
        <stakeholder id="STK_2" revision="1" dateCreated="2009-01-04T04:14:07" createdBy="USR_5">
            <annotations/>
            <goals/>
            <projectPermissions/>
            <user id="USR_4">
                <username>assistant</username>
                <password>f549cd73f694aa6f5541b4ae30894eea</password>
                <name>Analysis Assistant</name>
                <emailAddress>rreganjr@acm.org</emailAddress>
                <organization name="Requel"/>
                <userRoles>
                    <projectUserRole>
                        <userPermissions/>
                    </projectUserRole>
                </userRoles>
                <editable>false</editable>
            </user>
        </stakeholder>
        <stakeholder id="STK_3" revision="2" dateCreated="2009-01-05T02:17:44" createdBy="USR_5">
            <annotations/>
            <goals>
                <goalRef>GOL_10</goalRef>
            </goals>
            <name>Harvard University</name>
            <projectPermissions/>
        </stakeholder>
        <stakeholder id="STK_4" revision="1" dateCreated="2009-01-05T03:00:34" createdBy="USR_5">
            <annotations/>
            <goals/>
            <projectPermissions/>
            <user id="USR_3">
                <username>project</username>
                <password>46f86faa6bbf9ac94a7e459509a20ed0</password>
                <name>Builtin Project User</name>
                <emailAddress>rreganjr@acm.org</emailAddress>
                <organization name="Requel"/>
                <userRoles>
                    <projectUserRole>
                        <userPermissions>
                            <userPermission userRoleType="edu.harvard.fas.rregan.requel.project.ProjectUserRole" name="createProjects" id="PRM_1"/>
                        </userPermissions>
                    </projectUserRole>
                </userRoles>
                <editable>true</editable>
            </user>
        </stakeholder>
        <stakeholder id="STK_1" revision="2" dateCreated="2009-01-04T04:14:07" createdBy="USR_5">
            <annotations/>
            <goals/>
            <projectPermissions>
                <projectPermission permissionType="Edit" entityType="edu.harvard.fas.rregan.requel.project.Stakeholder"/>
                <projectPermission permissionType="Grant" entityType="edu.harvard.fas.rregan.requel.annotation.Annotation"/>
                <projectPermission permissionType="Edit" entityType="edu.harvard.fas.rregan.requel.project.Scenario"/>
                <projectPermission permissionType="Edit" entityType="edu.harvard.fas.rregan.requel.project.ReportGenerator"/>
                <projectPermission permissionType="Edit" entityType="edu.harvard.fas.rregan.requel.project.ProjectTeam"/>
                <projectPermission permissionType="Grant" entityType="edu.harvard.fas.rregan.requel.project.ReportGenerator"/>
                <projectPermission permissionType="Edit" entityType="edu.harvard.fas.rregan.requel.project.UseCase"/>
                <projectPermission permissionType="Edit" entityType="edu.harvard.fas.rregan.requel.project.GlossaryTerm"/>
                <projectPermission permissionType="Edit" entityType="edu.harvard.fas.rregan.requel.project.Goal"/>
                <projectPermission permissionType="Edit" entityType="edu.harvard.fas.rregan.requel.annotation.Annotation"/>
                <projectPermission permissionType="Grant" entityType="edu.harvard.fas.rregan.requel.project.Goal"/>
                <projectPermission permissionType="Grant" entityType="edu.harvard.fas.rregan.requel.project.Scenario"/>
                <projectPermission permissionType="Grant" entityType="edu.harvard.fas.rregan.requel.project.ProjectTeam"/>
                <projectPermission permissionType="Edit" entityType="edu.harvard.fas.rregan.requel.project.Story"/>
                <projectPermission permissionType="Grant" entityType="edu.harvard.fas.rregan.requel.project.Story"/>
                <projectPermission permissionType="Grant" entityType="edu.harvard.fas.rregan.requel.project.GlossaryTerm"/>
                <projectPermission permissionType="Grant" entityType="edu.harvard.fas.rregan.requel.project.Actor"/>
                <projectPermission permissionType="Edit" entityType="edu.harvard.fas.rregan.requel.project.Actor"/>
                <projectPermission permissionType="Grant" entityType="edu.harvard.fas.rregan.requel.project.UseCase"/>
                <projectPermission permissionType="Grant" entityType="edu.harvard.fas.rregan.requel.project.Stakeholder"/>
            </projectPermissions>
            <user id="USR_5">
                <username>rreganjr</username>
